name: QuickJSKit
attributes:
  CLASSPREFIX: QJS
options:
  bundleIdPrefix: top.ourfor.lib
  developmentLanguage: en
settings:
targets:
  QuickJSKit:
    type: library.static
    platform: iOS
    deploymentTarget: "8.0"
    scheme:
      testTargets:
        - QuickJSKitTests
    sources:
      - path: quickjs/quickjs.c
      - path: quickjs/cutils.c
      - path: quickjs/libbf.c
      - path: quickjs/libregexp.c
      - path: quickjs/libunicode.c
      - path: quickjs/quickjs-libc.c
      - path: quickjs/unicode_gen.c
      - path: quickjs/quickjs.h
      - path: quickjs/quickjs-libc.h
      - path: quickjs/quickjs-atom.h
      - path: QuickJSKit
        excludes:
    settings:
      INFOPLIST_FILE: QuickJSKit/Info.plist
      GCC_PREFIX_HEADER: QuickJSKit/PrefixHeader.pch
      OTHER_CFLAGS: $(inherited) -DCONFIG_VERSION=\"2021-03-27\"
      ENABLE_BITCODE: YES
      TARGETED_DEVICE_FAMILY: 1
      PRODUCT_BUNDLE_IDENTIFIER: top.ourfor.lib.QuickJSKit
  QuickJSKitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "8.0"
    sources: QuickJSKitTests
    dependencies:
      - target: QuickJSKit

